name = "dropin-chat"
main = "index.js"
compatibility_date = "2024-01-01"
preview_urls = false

[[kv_namespaces]]
binding = "CHAT_KV"
id = "e8df3751ad8b4cdda353683b97e08f09"

[[kv_namespaces]]
binding = "REVIEWS_KV"
id = "1185fa64f2c14b508278cc06b24eb0af"

[[kv_namespaces]]
binding = "BUILDKIT_KV"
id = "214959dc21244082b3e80493a847ffd2"

[[kv_namespaces]]
binding = "SHARE_CACHE_KV"
id = "09c09aeec9b7423ca162e57c2af8cd36"

[triggers]
crons = ["0 14 * * *"]
